package POJOS;
// Generated 31-ago-2016 10:38:15 by Hibernate Tools 3.6.0



/**
 * PagoDos generated by hbm2java
 */
public class PagoDos  implements java.io.Serializable {


     private int id;
     private String conceptCode;
     private String account;
     private String subtotalAmount;
     private String dv;
     private String folio;
     private String estatus;
     private String terminal;

    public PagoDos() {
    }

	
    public PagoDos(int id, String conceptCode) {
        this.id = id;
        this.conceptCode = conceptCode;
    }
    public PagoDos(int id, String conceptCode, String account, String subtotalAmount, String dv, String folio, String estatus, String terminal) {
       this.id = id;
       this.conceptCode = conceptCode;
       this.account = account;
       this.subtotalAmount = subtotalAmount;
       this.dv = dv;
       this.folio = folio;
       this.estatus = estatus;
       this.terminal = terminal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getConceptCode() {
        return this.conceptCode;
    }
    
    public void setConceptCode(String conceptCode) {
        this.conceptCode = conceptCode;
    }
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }
    public String getSubtotalAmount() {
        return this.subtotalAmount;
    }
    
    public void setSubtotalAmount(String subtotalAmount) {
        this.subtotalAmount = subtotalAmount;
    }
    public String getDv() {
        return this.dv;
    }
    
    public void setDv(String dv) {
        this.dv = dv;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }




}


