package POJOS;
// Generated 25-ago-2016 12:10:21 by Hibernate Tools 3.6.0



/**
 * PagoDos generated by hbm2java
 */
public class PagoDos  implements java.io.Serializable {


     private int id;
     private String conceptCode;
     private String phone;
     private String subtotalAmount;
     private String dv;
     private String folio;
     private String estatus;

    public PagoDos() {
    }

	
    public PagoDos(int id, String conceptCode) {
        this.id = id;
        this.conceptCode = conceptCode;
    }
    public PagoDos(int id, String conceptCode, String phone, String subtotalAmount, String dv, String folio, String estatus) {
       this.id = id;
       this.conceptCode = conceptCode;
       this.phone = phone;
       this.subtotalAmount = subtotalAmount;
       this.dv = dv;
       this.folio = folio;
       this.estatus = estatus;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getConceptCode() {
        return this.conceptCode;
    }
    
    public void setConceptCode(String conceptCode) {
        this.conceptCode = conceptCode;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getSubtotalAmount() {
        return this.subtotalAmount;
    }
    
    public void setSubtotalAmount(String subtotalAmount) {
        this.subtotalAmount = subtotalAmount;
    }
    public String getDv() {
        return this.dv;
    }
    
    public void setDv(String dv) {
        this.dv = dv;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }




}


