package POJOS;
// Generated 31-ago-2016 10:38:15 by Hibernate Tools 3.6.0



/**
 * Recargas generated by hbm2java
 */
public class Recargas  implements java.io.Serializable {


     private int id;
     private String conceptCode;
     private String phone;
     private String subtotalAmount;
     private String folio;
     private String estatus;
     private String terminal;

    public Recargas() {
    }

	
    public Recargas(int id, String conceptCode) {
        this.id = id;
        this.conceptCode = conceptCode;
    }
    public Recargas(int id, String conceptCode, String phone, String subtotalAmount, String folio, String estatus, String terminal) {
       this.id = id;
       this.conceptCode = conceptCode;
       this.phone = phone;
       this.subtotalAmount = subtotalAmount;
       this.folio = folio;
       this.estatus = estatus;
       this.terminal = terminal;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getConceptCode() {
        return this.conceptCode;
    }
    
    public void setConceptCode(String conceptCode) {
        this.conceptCode = conceptCode;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getSubtotalAmount() {
        return this.subtotalAmount;
    }
    
    public void setSubtotalAmount(String subtotalAmount) {
        this.subtotalAmount = subtotalAmount;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(String terminal) {
        this.terminal = terminal;
    }




}


